# Generated by Django 4.2.2 on 2024-03-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_teamresume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamresume',
            options={'verbose_name': 'پروژه تیم', 'verbose_name_plural': 'پروژه های تیم'},
        ),
    ]
