# Generated by Django 4.2.2 on 2024-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('سایت و وبلاگ', 'سایت و وبلاگ'), ('برنامه های دسکتاپ', 'برنامه های دسکتاپ'), ('برنامه های موبایل', 'برنامه های موبایل'), ('کارهای مربوط به بخش وب (رسپانسیو سازی و ...)', 'کارهای مربوط به بخش وب (رسپانسیو سازی و ...)'), ('سایر', 'سایر')], default='انتخاب کنید', max_length=50)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست ',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
    ]
