# Generated by Django 4.2.2 on 2024-03-12 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('سایت و وبلاگ', 'سایت و وبلاگ'), ('برنامه های دسکتاپ', 'برنامه های دسکتاپ'), ('برنامه های موبایل', 'برنامه های موبایل'), ('کارهای مربوط به بخش وب (رسپانسیو سازی و ...)', 'کارهای مربوط به بخش وب (رسپانسیو سازی و ...)'), ('سایر', 'سایر')], default='انتخاب کنید', max_length=50)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'درخواست ',
                'verbose_name_plural': 'درخواست ها',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='full_name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('role', models.CharField(blank=True, max_length=30, null=True, verbose_name='role')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='linkedin')),
                ('github', models.URLField(blank=True, null=True, verbose_name='github')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='telegram')),
                ('email', models.EmailField(blank=True, max_length=220, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('resume_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('shot_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('percent', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='members.team')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
    ]
